import React,{useEffect,useState} from "react";
import {api} from "./api.js";
import StatusBadge from "./StatusBadge.jsx";
import "./cn1_cn4.css";

export default function Web3ReportPage(){
 const [studentId,setStudentId]=useState("HS001");const [topics,setTopics]=useState([]);const [topicId,setTopicId]=useState("");const [file,setFile]=useState(null);const [reports,setReports]=useState([]);const [msg,setMsg]=useState("");const [web3,setWeb3]=useState(null);const [verify,setVerify]=useState(null);const [busy,setBusy]=useState(false);
 const load=async(id=studentId)=>{const [t,r,w]=await Promise.all([api.get("/topics"),api.get(`/reports?studentId=${encodeURIComponent(id)}`),api.get("/web3/status")]);setTopics(t.data);setReports(r.data);setWeb3(w.data);if(!topicId&&t.data[0])setTopicId(t.data[0]._id)};useEffect(()=>{load()},[]);
 const submit=async e=>{e.preventDefault();if(!file)return setMsg("Vui lòng chọn PDF/DOC/DOCX.");setBusy(true);setMsg("");setVerify(null);const fd=new FormData();fd.append("file",file);fd.append("topicId",topicId);fd.append("studentId",studentId);try{const {data}=await api.post("/reports/submit",fd);setMsg(`Nộp thành công. CID: ${data.ipfsCid}`);setFile(null);await load()}catch(err){setMsg(err.response?.data?.message||err.message);await load()}finally{setBusy(false)}};
 const check=async id=>{try{setVerify((await api.get(`/reports/${id}/verify`)).data)}catch(err){setVerify({valid:false,error:err.response?.data?.message||err.message})}};
 return <><header className="page-header"><div><p className="eyebrow">CHỨC NĂNG 04</p><h1>Lưu trữ & xác thực tài liệu Web3</h1><p>IPFS lưu nội dung; Smart Contract ghi CID/hash và thời điểm nộp để kiểm chứng.</p></div><div className="student-box"><label>Mã học sinh<input value={studentId} onChange={e=>setStudentId(e.target.value)}/></label><button onClick={()=>load(studentId)}>Tải dữ liệu</button></div></header>
 <div className="web3-status"><div><span>IPFS</span><b>{web3?.ipfs?.mode?.toUpperCase()||"..."}</b><small>{web3?.ipfs?.configured?"Đã cấu hình":"Thiếu cấu hình"}</small></div><div><span>Blockchain</span><b>{web3?.blockchain?.mode?.toUpperCase()||"..."}</b><small>{web3?.blockchain?.reachable?"Sẵn sàng":"Không kết nối"}</small></div></div>
 <section className="card accent-card"><div className="card-head"><div><h2>Nộp báo cáo cuối</h2><p>Base hiện để mock nhằm chạy giao diện ổn định; chuyển sang real sau khi cấu hình IPFS/Hardhat.</p></div></div><form className="upload-form" onSubmit={submit}><label>Đề tài<select value={topicId} onChange={e=>setTopicId(e.target.value)}>{topics.map(t=><option key={t._id} value={t._id}>{t.title}</option>)}</select></label><label className="file-drop"><span>{file?file.name:"Chọn PDF/DOC/DOCX (≤10MB)"}</span><input type="file" accept=".pdf,.doc,.docx" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="primary" disabled={busy}>{busy?"Đang xử lý...":"Nộp & xác thực"}</button></form>{msg&&<div className="notice">{msg}</div>}</section>
 {verify&&<section className={`verify-result ${verify.valid?"valid":"invalid"}`}><h3>{verify.valid?"✓ Tài liệu hợp lệ":"⚠ Chưa xác minh được"}</h3>{verify.error?<p>{verify.error}</p>:<><p><b>CID:</b> <span className="mono">{verify.report?.ipfsCid}</span></p><p><b>File hash:</b> <span className="mono">{verify.report?.fileHash}</span></p><p><b>Transaction:</b> <span className="mono">{verify.report?.transactionHash}</span></p></>}</section>}
 <section className="card"><h2>Lịch sử báo cáo</h2><div className="table-wrap"><table><thead><tr><th>Tệp</th><th>CID</th><th>Transaction</th><th>Thời điểm</th><th>Trạng thái</th><th>Kiểm chứng</th></tr></thead><tbody>{reports.map(r=><tr key={r._id}><td><b>{r.originalName}</b><small>{Math.round(r.fileSize/1024)} KB</small></td><td className="mono compact">{r.ipfsCid||"-"}</td><td className="mono compact">{r.transactionHash||"-"}</td><td>{new Date(r.submittedAt).toLocaleString("vi-VN")}</td><td><StatusBadge value={r.web3Status}/></td><td><button onClick={()=>check(r._id)}>Kiểm chứng</button></td></tr>)}</tbody></table></div></section></>;
}
